name: Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: -1  # 全履歴を取得してタグを確認できるようにする

      - name: Create tag
        run: |
          YY=$(date +%y)
          MM=$(date +%m)
          REV=0
          while git show-ref --tags | grep -q "refs/tags/${YY}.${MM}.${REV}"; do
            REV=$((REV+1))
          done
          echo "RELEASE_VERSION=${YY}.${MM}.${REV}" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          git archive HEAD --format=zip --output=latex-template-${{ env.RELEASE_VERSION }}.zip

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ env.RELEASE_VERSION }}
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} latex-template-${TAG}.zip --generate-notes